apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lets-encrypt-stage
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: git@github.com:4chain-ag/spv-wallet-regression.git
    targetRevision: HEAD
    path: charts/lets-encrypt-stage
