apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-definitions-mount
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/4chain-ag/spv-wallet-regression.git
    targetRevision: HEAD
    path: devops-tools-defs
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
