apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/instance: uptime-kuma-main
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: monitor
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: kubectl
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: uptime-kuma-main
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: uptime-kuma
        app.kubernetes.io/instance: uptime-kuma-main
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: monitor
        app.kubernetes.io/part-of: monitoring
        app.kubernetes.io/managed-by: kubectl
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:1.23.13
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "1000m"
          ports:
            - containerPort: 3001
              name: web
              protocol: TCP
          volumeMounts:
            - name: pvc
              mountPath: /app/data
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: uptime-kuma-pvc
