spv-wallet-stack:
  global:
    storageClass: openebs-hostpath
    ingress:
      className: traefik
      additionalAnnotations:
        cert-manager.io/cluster-issuer: lets-encrypt

  spv-wallet:
    enabled: true
    image:
      repository: bsvb/spv-wallet
      pullPolicy: IfNotPresent
      tag: ''
    config:
      auth:
        admin_key: xpub661MyMwAqRbcFgfmdkPgE2m5UjHXu9dj124DbaGLSjaqVESTWfCD4VuNmEbVPkbYLCkykwVZvmA8Pbf8884TQr1FgdG2nPoHR8aB36YdDQh

  block-headers-service:
    enabled: true

  spv-wallet-admin:
    enabled: false

  spv-wallet-web:
    enabled: false
