spv-wallet-stack:
  global:
    storageClass: openebs-hostpath
    adminkeySecret: ""
    ingress:
      className: traefik
      additionalAnnotations:
#        cert-manager.io/cluster-issuer: lets-encrypt-wildcard

  spv-wallet:
    enabled: true
    spv-wallet-admin-keygen:
      enabled: false
    image:
      repository: bsvb/spv-wallet
      pullPolicy: IfNotPresent
      tag: ''
    config:
      auth:
        admin_key: xpub661MyMwAqRbcFgfmdkPgE2m5UjHXu9dj124DbaGLSjaqVESTWfCD4VuNmEbVPkbYLCkykwVZvmA8Pbf8884TQr1FgdG2nPoHR8aB36YdDQh

  block-headers-service:
    enabled: true
    postgresql:
      enabled: false
    ingress:
      enabled: false

  spv-wallet-admin:
    enabled: false

  spv-wallet-web:
    enabled: false
