apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-read-secret
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-read-secret
  namespace: default
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
roleRef:
  kind: Role
  name: cert-manager-read-secret
  apiGroup: rbac.authorization.k8s.io
