apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
  namespace: default
spec:
  secretName: wildcard-tls
  issuerRef:
    name: lets-encrypt-wildcard
    kind: ClusterIssuer
  commonName: "*.regression.4chain.pl"
  dnsNames:
  - "*.regression.4chain.pl"
