apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
  namespace: traefik
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: "*.regression.cleanchain.org"
  dnsNames:
  - "regression.cleanchain.org"
  - "*.regression.cleanchain.org"
