name: Regression tests for spv-wallet

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA'
        required: true
        default: 'latest'
      image_tag:
        description: 'Docker Image Tag'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ArgoCD CLI
        run: |
          curl -sLO https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          sudo mv argocd-linux-amd64 /usr/local/bin/argocd

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Log in to ArgoCD
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        run: |
          argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure

      - name: Deploy SQLite Instance
        run: |
          COMMIT_SHA=${{ github.event.inputs.commit_sha }}
          DOMAIN_NAME="test-${COMMIT_SHA}-sqlite.dev.4chain.space"
          helm upgrade --install spv-wallet-instance-sqlite ./charts/spv-wallet-regression-sqlite \
            --set global.domainName=${DOMAIN_NAME} \
            --set spv-wallet.image.tag=${{ github.event.inputs.image_tag }}
          argocd app create spv-wallet-instance-sqlite \
            --repo https://github.com/${{ github.repository }} \
            --path charts/spv-wallet-regression-sqlite \
            --dest-server https://kubernetes
