name: Regression tests for spv-wallet

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TEST_ID: ${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ArgoCD CLI
        run: |
          curl -sLO https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          sudo mv argocd-linux-amd64 /usr/local/bin/argocd

      - name: Log in to ArgoCD
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        run: |
          argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure --grpc-web

      - name: Deploy SQLite Instance
        run: |
          DOMAIN_NAME="test-${TEST_ID}-sqlite.dev.4chain.space"
          argocd app create reg-sl-${TEST_ID} \
            --repo https://github.com/${{ github.repository }} \
            --path charts/spv-wallet-regression-sqlite \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace sqlite-instance \
            --revision HEAD \
            --sync-policy automated \
            --upsert \
            --grpc-web \
            --helm-set global.domainName=${DOMAIN_NAME} \
            --helm-set spv-wallet-stack.spv-wallet.image.tag=${{ github.event.inputs.image_tag }}
        shell: bash

      - name: Deploy Postgres Instance
        run: |
          DOMAIN_NAME="test-${TEST_ID}-postgres.dev.4chain.space"
          argocd app create reg-pg-${TEST_ID} \
            --repo https://github.com/${{ github.repository }} \
            --path charts/spv-wallet-regression-postgres \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace postgres-instance \
            --revision HEAD \
            --sync-policy automated \
            --upsert \
            --grpc-web \
            --helm-set global.domainName=${DOMAIN_NAME} \
            --helm-set spv-wallet-stack.spv-wallet.image.tag=${{ github.event.inputs.image_tag }}
        shell: bash

      - name: Wait for Applications to be Healthy
        run: |
          sleep 270  # Sleep for 4:30 minutes (270 seconds)
          for i in {1..3}; do  # Check 3 times at larger intervals
            STATUS_SQLITE=$(argocd app get reg-sl-${TEST_ID} --grpc-web -o json | jq -r '.status.health.status')
            STATUS_POSTGRES=$(argocd app get reg-pg-${TEST_ID} --grpc-web -o json | jq -r '.status.health.status')
            SYNC_SQLITE=$(argocd app get reg-sl-${TEST_ID} --grpc-web -o json | jq -r '.status.sync.status')
            SYNC_POSTGRES=$(argocd app get reg-pg-${TEST_ID} --grpc-web -o json | jq -r '.status.sync.status')
            if [[ "$STATUS_SQLITE" == "Healthy" && "$STATUS_POSTGRES" == "Healthy" && "$SYNC_SQLITE" == "Synced" && "$SYNC_POSTGRES" == "Synced" ]]; then
              echo "Both applications are synced and healthy"
              break
            fi
            if [[ $i -eq 3 ]]; then  # If final check and still not healthy, fail
              echo "Applications did not become healthy and synced in time"
              exit 1
            fi
            echo "Waiting for applications to be healthy and synced..."
            sleep 120  # Wait for 2 minutes before next check
          done
        shell: bash

      - name: Perform Task
        run: echo "Applications are synced and healthy. Performing task..."

      - name: Remove SQLite Instance
        run: argocd app delete reg-sl-${TEST_ID} --yes --grpc-web

      - name: Remove Postgres Instance
        run: argocd app delete reg-pg-${TEST_ID} --yes --grpc-web
