name: Regression tests for spv-wallet

on:
  repository_dispatch:
    types: [regression_tests]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TEST_ID: ${{ github.event.client_payload.run_id }}
      IMAGE_TAG: ${{ github.event.client_payload.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ArgoCD CLI
        run: |
          curl -sLO https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          sudo mv argocd-linux-amd64 /usr/local/bin/argocd

      - name: Log in to ArgoCD
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        run: |
          argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure --grpc-web

      - name: Deploy SQLite Instance
        run: |
          DOMAIN_NAME="test-${TEST_ID}-sqlite.dev.4chain.space"
          argocd app create reg-sl-${TEST_ID} \
            --repo https://github.com/${{ github.repository }} \
            --path charts/spv-wallet-regression-sqlite \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace sqlite-instance \
            --revision HEAD \
            --sync-policy automated \
            --upsert \
            --grpc-web \
            --helm-set global.domainName=${DOMAIN_NAME} \
            --helm-set spv-wallet-stack.spv-wallet.image.tag=${{ env.IMAGE_TAG }}
            --helm-set spv-wallet-stack.spv-wallet.image.repository=wregulski/spv-wallet
        shell: bash

      - name: Deploy Postgres Instance
        run: |
          DOMAIN_NAME="test-${TEST_ID}-postgres.dev.4chain.space"
          argocd app create reg-pg-${TEST_ID} \
            --repo https://github.com/${{ github.repository }} \
            --path charts/spv-wallet-regression-postgres \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace postgres-instance \
            --revision HEAD \
            --sync-policy automated \
            --upsert \
            --grpc-web \
            --helm-set global.domainName=${DOMAIN_NAME} \
            --helm-set spv-wallet-stack.spv-wallet.image.tag=${{ env.IMAGE_TAG }}
            --helm-set spv-wallet-stack.spv-wallet.image.repository=wregulski/spv-wallet
        shell: bash

      - name: Wait for Applications to be Healthy
        id: wait_for_apps
        run: |
          sleep 270
          for i in {1..3}; do
            STATUS_SQLITE=$(argocd app get reg-sl-${TEST_ID} --grpc-web -o json | jq -r '.status.health.status')
            STATUS_POSTGRES=$(argocd app get reg-pg-${TEST_ID} --grpc-web -o json | jq -r '.status.health.status')
            SYNC_SQLITE=$(argocd app get reg-sl-${TEST_ID} --grpc-web -o json | jq -r '.status.sync.status')
            SYNC_POSTGRES=$(argocd app get reg-pg-${TEST_ID} --grpc-web -o json | jq -r '.status.sync.status')
            if [[ "$STATUS_SQLITE" == "Healthy" && "$STATUS_POSTGRES" == "Healthy" && "$SYNC_SQLITE" == "Synced" && "$SYNC_POSTGRES" == "Synced" ]]; then
              echo "Both applications are synced and healthy"
              echo "::set-output name=app_status::healthy"
              break
            fi
            if [[ $i -eq 3 ]]; then
              echo "Applications did not become healthy and synced in time"
              echo "::set-output name=app_status::unhealthy"
            fi
            echo "Waiting for applications to be healthy and synced..."
            sleep 120
          done
        shell: bash

      - name: Install Go
        run: |
          wget https://golang.org/dl/go1.22.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.22.5.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
        shell: bash

      - name: Run Operator
        id: run_operator
        run: |
          export PATH=$PATH:/usr/local/go/bin
          go run operator.go test-${TEST_ID}-sqlite.dev.4chain.space test-${TEST_ID}-postgres.dev.4chain.space
        shell: bash

      - name: Install Task
        run: |
          sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
        shell: bash

      - name: Download and Run External Tests
        run: |
          git clone https://github.com/4chain-ag/spv-wallet-regression.git
          cd spv-wallet-regression
          task regression-tests
        shell: bash

      - name: Fetch Logs on Failure
        if: ${{ failure() || steps.wait_for_apps.outputs.app_status == 'unhealthy' }}
        run: |
          argocd app logs reg-sl-${TEST_ID} --grpc-web > reg-sl-${TEST_ID}.log
          argocd app logs reg-pg-${TEST_ID} --grpc-web > reg-pg-${TEST_ID}.log
        shell: bash

      - name: Remove SQLite Instance
        run: argocd app delete reg-sl-${TEST_ID} --yes --grpc-web

      - name: Remove Postgres Instance
        run: argocd app delete reg-pg-${TEST_ID} --yes --grpc-web
