name: 'Test changes in this repository'

on:
  workflow_dispatch:
    inputs:
      keep_instances:
        description: 'When should it keep instances created during tests?'
        required: true
        default: 'never'
        type: choice
        options:
          - 'always'
          - 'failure'
          - 'never'

  pull_request:
    types: [labeled]

jobs:
  test:
    if: >
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'pull_request' && github.event.label.name == 'regression-tests')
    uses: ./.github/workflows/run-regression-tests.yaml
    with:
      image_tag: 'latest'
      run_id: 't${{ github.run_id }}-${{ github.run_attempt }}'
      keep_instances: ${{ inputs.keep_instances }}
    secrets:
      MASTER_INSTANCE_URL: ${{ secrets.MASTER_INSTANCE_URL }}
      MASTER_INSTANCE_XPRIV: ${{ secrets.MASTER_INSTANCE_XPRIV }}
      BLOCK_HEADERS_SERVICE_URL: ${{ secrets.BLOCK_HEADERS_SERVICE_URL }}
      BLOCK_HEADERS_SERVICE_AUTH_TOKEN: ${{ secrets.BLOCK_HEADERS_SERVICE_AUTH_TOKEN }}
      ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
      ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
      ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
